name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test-master:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Test Master
        uses: cuzfrog/setup-kubectl@master
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          run: |
            files=""
            for file in test/app.pvc.yml test/app.service.yml; do
              files="$files -f $file"
            done
            echo "kubectl apply $files"
            kubectl apply --dry-run=client $files

  test-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Test PR
        uses: ./
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          run: |
            kubectl --dry-run=client apply -f test/app.pvc.yml
            kubectl --dry-run=client apply -f test/app.service.yml
