name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test1
        uses: ./
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          run: |
            files=""
            for file in test/app.pvc.yml test/app.service.yml; do
              files="$files -f $file"
            done
            echo "kubectl apply $files"
            kubectl apply --dry-run=client $files
      - name: Test3
        uses: ./
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          run: |
            envsubst <test/template

  move-tag:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Move tag
        run: |
          git push --delete origin v1
          git tag v1 ${{ github.sha }}
          git push origin v1
